server:
  port: 9093

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 'feva@1991es'
        platform: mysql
        url: jdbc:mysql://localhost/clientes?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: admin
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: false
        hibernate:
            ddl-auto: update
        show-sql: true

