server:
  port: 9080

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

zuul:
  routes:
    cliente:
      path: /services/cliente/all
      url: http://localhost:9092/api/v1/cliente/all

spring:
  application:
    name: zuul-service

# Increase the Hystrix timeout to 60s (for all)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  
